version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing prerequisites..."

  pre_build:
    commands:
      - echo "Validating file structure..."
      - test -f appspec.yml || (echo "❌ appspec.yml is missing!" && exit 1)
      - echo "✅ appspec.yml is present."

  build:
    commands:
      - echo "Copying appspec.yml to root..."
      - cp appspec.yml ./appspec.yml
      - echo "✅ Done copying."

artifacts:
  files:
    - appspec.yml
    - pipeline/myapp/**/*
