version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-web-app

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      runas: ubuntu
