version: 0.0
os: linux
files:
  - source: pipeline/myapp/
    destination: /home/ubuntu/myapp

hooks:
  BeforeInstall:
    - location: pipeline/myapp/scripts/install_dependencies.sh
      runas: ubuntu
  AfterInstall:
    - location: pipeline/myapp/scripts/start_server.sh
      runas: ubuntu
